### ISSUE TITLE
Linux A20-OLinuXino 3.4.103-00033-g9a1cd03-dirty

### ISSUE THREAD

**Issue by Adportas** [hadess/rtl8723bs#123]
Hello
Is there a way to build this software in kernel Linux A20-OLinuXino 3.4.103-00033-g9a1cd03-dirty
We get this error message at compile time:
/home/daniel/Proyectos/A20/rtl8723bs/include/ioctl_cfg80211.h:21:2: error: #error This driver only works with kernel 3.19 and later
Thank's in advance
Daniel
![captura de pantalla de 2017-03-31 10-29-04](https://cloud.githubusercontent.com/assets/26261880/24562463/452dd89e-1621-11e7-95cc-f35ac3fd3234.png)

**Comment by hadess** [comment]
No, the error message says it all, you need a newer kernel.

**Comment by Adportas** [comment]
Thanks for your response, do you know of any Kernel supporting A20 flashable from NAND that I could use for this? I can’t find anything beyond 3.4.x for A20 that supports both NAND and this wi-fi module.

**Comment by Adportas** [comment]
We are working with an A20(an ARM based SOC) SOM with sunxi linux where all the used kernels are 3.4.X and i don't find any with version 3.19.* available, can you give some tips on this, I’am not familiarized with the procedure to satisfy the required version in this scenario
