### ISSUE TITLE
make error: "This driver only works with kernel 4.0" received.

### ISSUE THREAD

**Issue by kylebu** [hadess/rtl8723bs#14]
I have been using this driver for a HP Stream 7 Bay Trail tablet with Ubuntu 14.10 and the 3.16 kernel and it has worked well.  I did a fresh installation today however and got the below error during the make, I think it might have been introduced with the commit from 5 days ago possibly.  Is the driver not going to work with 3.16 anymore?  The driver at: https://github.com/codeTom/rtl8723bs luckily worked okay so I am using that now.  Thank you.

make[1]: Entering directory '/usr/src/linux-headers-3.16.0-33-generic'
  CC [M]  /home/kyle/rtl8723as_BAD/core/rtw_cmd.o
In file included from /home/kyle/rtl8723as_BAD/include/drv_types.h:87:0,
                 from /home/kyle/rtl8723as_BAD/core/rtw_cmd.c:22:
/home/kyle/rtl8723as_BAD/include/ioctl_cfg80211.h:24:2: error: #error This driver only works with kernel 4.0
 #error This driver only works with kernel 4.0
  ^
scripts/Makefile.build:257: recipe for target '/home/kyle/rtl8723as_BAD/core/rtw_cmd.o' failed
make[2]: *** [/home/kyle/rtl8723as_BAD/core/rtw_cmd.o] Error 1
Makefile:1345: recipe for target '_module_/home/kyle/rtl8723as_BAD' failed
make[1]: *** [_module_/home/kyle/rtl8723as_BAD] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-33-generic'
Makefile:232: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by hadess** [comment]
I'm not supporting older kernels, as the changes done in that other repo break ABI.

You can still get older versions of the driver through git.
